[package]
name = "message_bridge"
type = "contract"
authors = ["Aztec Pioneers"]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-devnet.20251212", directory="noir-projects/aztec-nr/aztec" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
nodash = { git = "https://github.com/olehmisar/nodash", tag = "v0.42.0" }
wormhole = { path = "../wormhole" }
